// name: { type: String, required: true },
// description: { type: String, required: true },
// price: { type: Number, required: true },
// stock: { type: Number, required: true },
// photo: { type: String, required: true },

require('dotenv').config()
require('./config/database')
const Cap = require('./models/Cap')


Cap.create({
    name: "Sand Camo Jet Cap",
    description: "",
    photo: "https://ithk-pro-itmall-item.oss-cn-hongkong.aliyuncs.com/2/product/0ZXCPM180011IBGX/0ZXCPM180011IBGX-pdp-1.JPG?x-oss-process=image/resize,m_pad,h_750,w_600/auto-orient,1/quality,Q_80",
    price: 137,
    stock: 30,
},
{
    name: "STA Ape Head Leather Patched Mesh Cap",
    description: "",
    photo: "https://ithk-pro-itmall-item.oss-cn-hongkong.aliyuncs.com/2/product/0ZXCPM180011JBKX/0ZXCPM180011JBKX-pdp-1.jpg?x-oss-process=image/resize,m_pad,h_750,w_600/auto-orient,1/quality,Q_80",
    price: 211,
    stock: 30,
},
{
    name: "SURFACE Panel Cap",
    description: "",
    photo: "https://ithk-pro-itmall-item.oss-cn-hongkong.aliyuncs.com/2/product/0ZXCPM180003JBGX/0ZXCPM180003JBGX-pdp-1.jpg?x-oss-process=image/resize,m_pad,h_750,w_600/auto-orient,1/quality,Q_80",
    price: 137,
    stock: 40,
},
{
    name: "Bathing Ape Corduroy Cap",
    description: "",
    photo: "https://ithk-pro-itmall-item.oss-cn-hongkong.aliyuncs.com/2/product/0ZXCPM180008JCCX/0ZXCPM180008JCCX-pdp-1.jpg?x-oss-process=image/resize,m_pad,h_750,w_600/auto-orient,1/quality,Q_80",
    price: 137,
    stock: 40,
},
{
    name: "X New Era Wrangler Label 9Fifty Snap Back Cap",
    description: "",
    photo: "https://ithk-pro-itmall-item.oss-cn-hongkong.aliyuncs.com/2/product/0ZXCPM180909IBLX/0ZXCPM180909IBLX-pdp-1.jpg?x-oss-process=image/resize,m_pad,h_750,w_600/auto-orient,1/quality,Q_80",
    price: 166,
    stock: 35,
},
{
    name: "X New Era 1st Camo 9 Fifty Cap",
    description: "",
    photo: "https://ithk-pro-itmall-item.oss-cn-hongkong.aliyuncs.com/2/product/0ZXCPMX80907IGRX/0ZXCPMX80907IGRX-pdp-1.jpg?x-oss-process=image/resize,m_pad,h_750,w_600/auto-orient,1/quality,Q_80",
    price: 166,
    stock: 35,
},
{
    name: "X New Era Ape Head 9 Fifty Cap",
    description: "",
    photo: "https://ithk-pro-itmall-item.oss-cn-hongkong.aliyuncs.com/2/product/0ZXCPMX80905IBLX/0ZXCPMX80905IBLX-pdp-1.jpg?x-oss-process=image/resize,m_pad,h_750,w_600/auto-orient,1/quality,Q_80",
    price: 153,
    stock: 40,
},
{
    name: "X New Era A Bathing Ape 9Twenty Cap",
    description: "",
    photo: "https://ithk-pro-itmall-item.oss-cn-hongkong.aliyuncs.com/2/product/0ZXCPM180908IBKX/0ZXCPM180908IBKX-pdp-1.jpg?x-oss-process=image/resize,m_pad,h_750,w_600/auto-orient,1/quality,Q_80",
    price: 137,
    stock: 40,
},
{
    name: "X A.P.C. Milo On APC Denim Cap",
    description: "",
    photo: "https://ithk-pro-itmall-item.oss-cn-hongkong.aliyuncs.com/2/product/0ZXCPM180902IBKX/0ZXCPM180902IBKX-pdp-1.jpg?x-oss-process=image/resize,m_pad,h_750,w_600/auto-orient,1/quality,Q_80",
    price: 108,
    stock: 40,
},
{
    name: "X A.P.C. Milo Cotton Cap",
    description: "",
    photo: "https://ithk-pro-itmall-item.oss-cn-hongkong.aliyuncs.com/2/product/0ZXCPM180901INYX/0ZXCPM180901INYX-pdp-1.jpg?x-oss-process=image/resize,m_pad,h_750,w_600/auto-orient,1/quality,Q_80",
    price: 108,
    stock: 40,
},
{
    name: "X New Era STA 59Fifty Cap",
    description: "",
    photo: "https://ithk-pro-itmall-item.oss-cn-hongkong.aliyuncs.com/2/product/0ZXCPM180015JBKX/0ZXCPM180015JBKX-pdp-1.jpg?x-oss-process=image/resize,m_pad,h_750,w_600/auto-orient,1/quality,Q_80",
    price: 182,
    stock: 30,
},
{
    name: "Tie Dye One Point Bucket Hat",
    description: "",
    photo: "https://ithk-pro-itmall-item.oss-cn-hongkong.aliyuncs.com/2/product/0ZXHTM181003JBKX/0ZXHTM181003JBKX-pdp-1.jpg?x-oss-process=image/resize,m_pad,h_750,w_600/auto-orient,1/quality,Q_80",
    price: 143,
    stock: 30,
},
{
    name: "Shark Jet Cap",
    description: "",
    photo: "https://ithk-pro-itmall-item.oss-cn-hongkong.aliyuncs.com/2/product/0ZXCPMX80005IBKX/0ZXCPMX80005IBKX-pdp-1.jpg?x-oss-process=image/resize,m_pad,h_750,w_600/auto-orient,1/quality,Q_80",
    price: 153,
    stock: 40,
},
{
    name: "1st Camo BAPE STA Mesh Cap",
    description: "",
    photo: "https://ithk-pro-itmall-item.oss-cn-hongkong.aliyuncs.com/2/product/0ZXCPM180018IGRX/0ZXCPM180018IGRX-pdp-1.jpg?x-oss-process=image/resize,m_pad,h_750,w_600/auto-orient,1/quality,Q_80",
    price: 127,
    stock: 40,
},
{
    name: "WGM Panel Cap",
    description: "",
    photo: "https://ithk-pro-itmall-item.oss-cn-hongkong.aliyuncs.com/2/product/0ZXCPMX80008IBKX/0ZXCPMX80008IBKX-pdp-1.jpg?x-oss-process=image/resize,m_pad,h_750,w_600/auto-orient,1/quality,Q_80",
    price: 127,
    stock: 40,
},
{
    name: "Color Camo Panel Hat",
    description: "",
    photo: "https://ithk-pro-itmall-item.oss-cn-hongkong.aliyuncs.com/2/product/0ZXHTM181013IGRX/0ZXHTM181013IGRX-pdp-1.jpg?x-oss-process=image/resize,m_pad,h_750,w_600/auto-orient,1/quality,Q_80",
    price: 133,
    stock: 35,
},
{
    name: "SURFACE Jet Cap",
    description: "",
    photo: "https://ithk-pro-itmall-item.oss-cn-hongkong.aliyuncs.com/2/product/0ZXCPM180014IBLX/0ZXCPM180014IBLX-pdp-1.jpg?x-oss-process=image/resize,m_pad,h_750,w_600/auto-orient,1/quality,Q_80",
    price: 127,
    stock: 35,
},
{
    name: "Stroke Camo Pocket Bucket Hat",
    description: "",
    photo: "https://ithk-pro-itmall-item.oss-cn-hongkong.aliyuncs.com/2/product/0ZXHTM181006IBKX/0ZXHTM181006IBKX-pdp-1.jpg?x-oss-process=image/resize,m_pad,h_750,w_600/auto-orient,1/quality,Q_80",
    price: 137,
    stock: 30,
},
{
    name: "BAPE Panel Cap",
    description: "",
    photo: "https://ithk-pro-itmall-item.oss-cn-hongkong.aliyuncs.com/2/product/0ZXCPM180007IBGX/0ZXCPM180007IBGX-pdp-1.jpg?x-oss-process=image/resize,m_pad,h_750,w_600/auto-orient,1/quality,Q_80",
    price: 137,
    stock: 30,
},
{
    name: "BAPE Lenticular Emblem Mesh Cap",
    description: "",
    photo: "https://ithk-pro-itmall-item.oss-cn-hongkong.aliyuncs.com/2/product/0ZXCPMX80004IBKX/0ZXCPMX80004IBKX-pdp-1.jpg?x-oss-process=image/resize,m_pad,h_750,w_600/auto-orient,1/quality,Q_80",
    price: 182,
    stock: 25,
},
)